### PR TITLE
PMD 'Design' ruleset

### PR DESCRIPTION
**Pull request by ThrawnCA**
The combined diff is pretty big, but you can check individual commits to get more of an idea.

### CODE REVIEW

**Comment by mebigfatguy** [comment]
looks good. lots of work, thanks!

**Comment by mebigfatguy** [comment]
after this merge, i see

report:
     [echo] <fbdelta>
     [echo] 	<fixed>
     [echo] 		<class name='JVR_Sample'>
     [echo] 			<bug type='JVR_JDBC_VENDOR_RELIANCE' count='1'/>
     [echo] 		</class>
     [echo] 		<class name='SCI_Sample'>
     [echo] 			<bug type='SCI_SYNCHRONIZED_COLLECTION_ITERATORS' count='2'/>
     [echo] 		</class>
     [echo] 	</fixed>
     [echo] 	<new>
     [echo] 	</new>
     [echo] </fbdelta>

from running ant sample_deltas

so it looks like some bugs were inadvertently reported as 'fixed'

**Comment by mebigfatguy** [comment]
6dc78527c9ab56e2a8bb060441c5df8930349604 fixes the JVR on

**Comment by ThrawnCA** [comment]
Hmm. The SyncCollectionIterators bug is puzzling.

Wait, here's a possibility. When I refactored the SEEN_LOAD logic into its own method, it looked like all branches except one would set the state to SEEN_NOTHING, so I put that at the top of the method. However, in hindsight, it occurs to me that there is in fact a path that doesn't override the state: if the called class is in java/util, but the method is not 'iterator'.

**Comment by mebigfatguy** [comment]
ah, if you could post a new patch that'd be great.

**Comment by mebigfatguy** [comment]
also, https://travis-ci.org/mebigfatguy/fb-contrib/jobs/171269641

**Comment by mebigfatguy** [comment]
oh never mind that was me, fixed

**Pull request merged**
