### PR TITLE
populate Git revision information in manifest

### PR DESCRIPTION
**Pull request by ThrawnCA**
Requires build number plugin 1.3, which requires at least Maven 2.2.1

Also requires Git repository to be configured as the developer connection, instead of ``svn.sourceforge.net``. Not sure which one is actually canonical?

### CODE REVIEW

**Comment by mebigfatguy** [comment]
can you switch all the scm stuff over to github?

**Comment by ThrawnCA** [comment]
What about the mailing lists?

**Comment by ThrawnCA** [comment]
Scm is done. Looks like the sourceforge mailing lists are still active, so I left those alone.

**Comment by mebigfatguy** [comment]
yeah, just scm, thanks

**Pull request merged**
