### PR TITLE
add unit testing for signature logic

### PR DESCRIPTION
**Pull request by ThrawnCA**

### CODE REVIEW

**Comment by ThrawnCA** [comment]
Does that mean that you're...moving toward Maven instead of Ant? :o

Happy to move things, but that may require using the build-helper plugin, so that we can specify multiple test source directories. Maven core lets you specify an arbitrary number of *resource* directories, but not Java source.

**Comment by ThrawnCA** [comment]
Um. When I said I'm happy to move things, I kind of meant *after* merging this...oh well, conflict resolution time.

So...I'll hold off on the pull request from my master branch for now, I guess.

**Comment by mebigfatguy** [comment]
i'm fine with the standard maven layout. i just don't want o have to figure out the maven voodoo to get it work. so lets go with src/main/java, src/test/java and src/samples/java

i've moved the main and samples over already, as you see.

**Comment by ThrawnCA** [comment]
OK...do you still want the samples to be compiled by Maven? I'd recommend it, as a syntax check and possible opportunity for future unit testing. If yes, then I'll configure the build-helper plugin.

**Comment by mebigfatguy** [comment]
do you still want the samples to be compiled by Maven?

yes, please.

**Pull request merged**
