### PR TITLE
introduce a SignatureBuilder to help construct method signatures

### PR DESCRIPTION
**Pull request by ThrawnCA**
- More verbose, but more self-documenting and less error-prone
- Define a number of commonly-used method signatures for reuse
- Also expand usage of constants for signature components
- ``SignatureUtils.classToSignature`` has been enhanced to handle primitives, arrays, and empty strings

### CODE REVIEW

**Comment by mebigfatguy** [comment]
is this the same?

-                if (getSigConstantOperand().startsWith("(Ljava/lang/String;)")) {
 +                if (getSigConstantOperand().startsWith(new SignatureBuilder().withParamTypes(Values.SLASHED_JAVA_LANG_STRING).withReturnType("").toString())) {

for instance it could match parseLong, parseInt etc, and have different return types.

**Comment by mebigfatguy** [comment]
ah withReturnType("") ok, got it.

**Comment by mebigfatguy** [comment]
maybe it would be better to explicitly reject withReturnType(""), (to catch errors) and provide withNoReturnType() or something

**Comment by ThrawnCA** [comment]
...and now you know why I've been turning up old issues with signatures :)

**Comment by mebigfatguy** [comment]
great work. (obviously found bunches)

**Comment by mebigfatguy** [comment]
thinking on this further, i'd like to try to avoid use of SignatureBuilder in sawOpcode or methods called from sawOpcode, so i'd be happy to add more constants to SignatureBuilder, or to the individual classes that need them. Let's continue to use SignatureBuilder, i'm just saying not dynamically in the method(s) themselves.

Obviously use in things like <init>, <clinit>, visitClassContext, visitMethod, visitCode is fine by me.

**Comment by ThrawnCA** [comment]
Happy to convert things to use constants when possible.

When signatures are, in fact, constructed dynamically, would it be better to change ``withParamTypes`` to reset the list, instead of appending, meaning that a single ``SignatureBuilder`` could be reused with different parameter types instead of creating a new one each time?

**Comment by mebigfatguy** [comment]
to me it does seem more natural that withParamTypes would reset the list

**Comment by ThrawnCA** [comment]
Also, the usage of ``toString`` to output the results is fairly intuitive, and consistent with eg ``StringBuilder``, but liable to trip ``STT_TOSTRING_STORED_IN_FIELD``. Should I change it to ``build``?

**Comment by mebigfatguy** [comment]
i'd vote yes

**Pull request merged**
